### ISSUE TITLE
OpenAPI and actuator endpoints are exclusion does not work

### ISSUE THREAD

**Issue by elg-entur** [entur/cloud-logging#67]
> By default [certain OpenAPI and actuator endpoints](https://github.com/entur/cloud-logging/blob/develop/gcp/request-response-spring-boot-starter-gcp-web/src/main/resources/logbook.gcp.web.properties) are excluded.

Does not work as expected, https://cloudlogging.app.goo.gl/naoCtAtpZ29AWaot8

## Workaround (written in yaml) 

https://github.com/zalando/logbook#example-configuration

```yaml
logbook:
  predicate:
    exclude:
      - path: /actuator/**
      - path: /favicon.*
      - path: /v2/api-docs/**
      - path: /v3/api-docs/**
      - path: /metrics
      - path: /swagger
```
